export interface Stock {
  symbol: string
  name: string
}

export const INDIAN_STOCKS: Stock[] = [
  { symbol: "20MICRONS", name: "20 Microns Limited" },
  { symbol: "21STCENMGM", name: "21st Century Management Services Limited" },
  { symbol: "360ONE", name: "360 ONE WAM LIMITED" },
  { symbol: "3IINFOLTD", name: "3i Infotech Limited" },
  { symbol: "3MINDIA", name: "3M India Limited" },
  { symbol: "3PLAND", name: "3P Land Holdings Limited" },
  { symbol: "5PAISA", name: "5Paisa Capital Limited" },
  { symbol: "63MOONS", name: "63 moons technologies limited" },
  { symbol: "A2ZINFRA", name: "A2Z Infra Engineering Limited" },
  { symbol: "AAATECH", name: "AAA Technologies Limited" },
  { symbol: "AADHARHFC", name: "Aadhar Housing Finance Limited" },
  { symbol: "AAKASH", name: "Aakash Exploration Services Limited" },
  { symbol: "AAREYDRUGS", name: "Aarey Drugs & Pharmaceuticals Limited" },
  { symbol: "AARON", name: "Aaron Industries Limited" },
  { symbol: "AARTECH", name: "Aartech Solonics Limited" },
  { symbol: "AARTIDRUGS", name: "Aarti Drugs Limited" },
  { symbol: "AARTIIND", name: "Aarti Industries Limited" },
  { symbol: "AARTIPHARM", name: "Aarti Pharmalabs Limited" },
  { symbol: "AARTISURF", name: "Aarti Surfactants Limited" },
  { symbol: "AARVEEDEN", name: "Aarvee Denims & Exports Limited" },
  { symbol: "AARVI", name: "Aarvi Encon Limited" },
  { symbol: "AAVAS", name: "Aavas Financiers Limited" },
  { symbol: "ABAN", name: "Aban Offshore Limited" },
  { symbol: "ABB", name: "ABB India Limited" },
  { symbol: "ABBOTINDIA", name: "Abbott India Limited" },
  { symbol: "ABCAPITAL", name: "Aditya Birla Capital Limited" },
  { symbol: "ABDL", name: "Allied Blenders and Distillers Limited" },
  { symbol: "ABFRL", name: "Aditya Birla Fashion and Retail Limited" },
  { symbol: "ABINFRA", name: "A B Infrabuild Limited" },
  { symbol: "ABMINTLLTD", name: "ABM International Limited" },
  { symbol: "ABREL", name: "Aditya Birla Real Estate Limited" },
  { symbol: "ABSLAMC", name: "Aditya Birla Sun Life AMC Limited" },
  { symbol: "ACC", name: "ACC Limited" },
  { symbol: "ACCELYA", name: "Accelya Solutions India Limited" },
  { symbol: "ACCURACY", name: "Accuracy Shipping Limited" },
  { symbol: "ACE", name: "Action Construction Equipment Limited" },
  { symbol: "ACEINTEG", name: "Ace Integrated Solutions Limited" },
  { symbol: "ACI", name: "Archean Chemical Industries Limited" },
  { symbol: "ACL", name: "Andhra Cements Limited" },
  { symbol: "ACLGATI", name: "Allcargo Gati Limited" },
  { symbol: "ACMESOLAR", name: "Acme Solar Holdings Limited" },
  { symbol: "ADANIENSOL", name: "Adani Energy Solutions Limited" },
  { symbol: "ADANIENT", name: "Adani Enterprises Limited" },
  { symbol: "ADANIGREEN", name: "Adani Green Energy Limited" },
  { symbol: "ADANIPORTS", name: "Adani Ports and Special Economic Zone Limited" },
  { symbol: "ADANIPOWER", name: "Adani Power Limited" },
  { symbol: "ADFFOODS", name: "ADF Foods Limited" },
  { symbol: "ADHUNIK", name: "Adhunik Industries Limited" },
  { symbol: "ADORWELD", name: "Ador Welding Limited" },
  { symbol: "AFFLE", name: "Affle (India) Limited" },
  { symbol: "AGCNET", name: "AGC Networks Limited" },
  { symbol: "AGRITECH", name: "Agri-Tech (India) Limited" },
  { symbol: "AHMEDFORGE", name: "Ahmed Forge Company Limited" },
  { symbol: "AJANTPHARM", name: "Ajanta Pharma Limited" },
  { symbol: "AKSHARCHEM", name: "Akshar Chem (India) Limited" },
  { symbol: "ALEMBICLTD", name: "Alembic Limited" },
  { symbol: "ALICON", name: "Alicon Castalloy Limited" },
  { symbol: "ALKYLAMINE", name: "Alkyl Amines Chemicals Limited" },
  { symbol: "ALLCARGO", name: "Allcargo Logistics Limited" },
  { symbol: "ALLSEC", name: "Allsec Technologies Limited" },
  { symbol: "AMARAJABAT", name: "Amara Raja Batteries Limited" },
  { symbol: "AMBUJACEM", name: "Ambuja Cements Limited" },
  { symbol: "AMDL", name: "Amdocs Limited" },
  { symbol: "AMJLAND", name: "AMJ Land Holdings Limited" },
  { symbol: "ANANTRAJ", name: "Anant Raj Limited" },
  { symbol: "ANGELONE", name: "Angel One Limited" },
  { symbol: "ANIKINDS", name: "Anik Industries Limited" },
  { symbol: "ANURAS", name: "Anuras Industries Limited" },
  { symbol: "APLLTD", name: "Alembic Pharmaceuticals Limited" },
  { symbol: "APOLLOHOSP", name: "Apollo Hospitals Enterprise Limited" },
  { symbol: "APOLLOTYRE", name: "Apollo Tyres Limited" },
  { symbol: "APTUS", name: "Aptus Value Housing Finance India Limited" },
  { symbol: "ARCHIDPLY", name: "Archidply Industries Limited" },
  { symbol: "ARVINDFASN", name: "Arvind Fashions Limited" },
  { symbol: "ARVINDLTD", name: "Arvind Limited" },
  { symbol: "ASAHIINDIA", name: "Asahi India Glass Limited" },
  { symbol: "ASHOKLEY", name: "Ashok Leyland Limited" },
  { symbol: "ASIANPAINT", name: "Asian Paints Limited" },
  { symbol: "ASTERDM", name: "Aster DM Healthcare Limited" },
  { symbol: "ASTRAL", name: "Astral Limited" },
  { symbol: "ASTRAMICRO", name: "Astra Microwave Products Limited" },
  { symbol: "ATUL", name: "Atul Limited" },
  { symbol: "AUBANK", name: "AU Small Finance Bank Limited" },
  { symbol: "AUSOMENT", name: "Ausom Enterprise Limited" },
  { symbol: "AUTOAXLES", name: "Automotive Axles Limited" },
  { symbol: "AUROPHARMA", name: "Aurobindo Pharma Limited" },
  { symbol: "AVANTIFEED", name: "Avanti Feeds Limited" },
  { symbol: "AXISBANK", name: "Axis Bank Limited" },
  { symbol: "BAJAJ-AUTO", name: "Bajaj Auto Limited" },
  { symbol: "BAJAJFINSV", name: "Bajaj Finserv Limited" },
  { symbol: "BAJFINANCE", name: "Bajaj Finance Limited" },
  { symbol: "BALKRISIND", name: "Balkrishna Industries Limited" },
  { symbol: "BALMLAWRIE", name: "Balmer Lawrie & Company Limited" },
  { symbol: "BALRAMCHIN", name: "Balrampur Chini Mills Limited" },
  { symbol: "BANDHANBNK", name: "Bandhan Bank Limited" },
  { symbol: "BANKBARODA", name: "Bank of Baroda" },
  { symbol: "BANKINDIA", name: "Bank of India" },
  { symbol: "MAHABANK", name: "Bank of Maharashtra" },
  { symbol: "BASF", name: "BASF India Limited" },
  { symbol: "BATAINDIA", name: "Bata India Limited" },
  { symbol: "BAYER", name: "Bayer CropScience Limited" },
  { symbol: "BAYERCROP", name: "Bayer CropScience Limited" },
  { symbol: "BEML", name: "BEML Limited" },
  { symbol: "BERGEPAINT", name: "Berger Paints India Limited" },
  { symbol: "BHARATFORG", name: "Bharat Forge Limited" },
  { symbol: "BHARATRAS", name: "Bharat Rasayan Limited" },
  { symbol: "BHARTIARTL", name: "Bharti Airtel Limited" },
  { symbol: "BHEL", name: "Bharat Heavy Electricals Limited" },
  { symbol: "BIOCON", name: "Biocon Limited" },
  { symbol: "BIRLACORPN", name: "Birla Corporation Limited" },
  { symbol: "BLISSGVS", name: "Bliss GVS Pharma Limited" },
  { symbol: "BLUESTARCO", name: "Blue Star Limited" },
  { symbol: "BOMDYEING", name: "Bombay Dyeing & Manufacturing Company Limited" },
  { symbol: "BOSCHLTD", name: "Bosch Limited" },
  { symbol: "BPCL", name: "Bharat Petroleum Corporation Limited" },
  { symbol: "BRITANNIA", name: "Britannia Industries Limited" },
  { symbol: "BSOFT", name: "Birlasoft Limited" },
  { symbol: "CADILAHC", name: "Cadila Healthcare Limited" },
  { symbol: "CAMS", name: "Computer Age Management Services Limited" },
  { symbol: "CANBK", name: "Canara Bank" },
  { symbol: "CAPLIPOINT", name: "Caplin Point Laboratories Limited" },
  { symbol: "CARBORUNIV", name: "Carborundum Universal Limited" },
  { symbol: "CARERATING", name: "Care Ratings Limited" },
  { symbol: "CASTROLIND", name: "Castrol India Limited" },
  { symbol: "CCL", name: "CCL Products (India) Limited" },
  { symbol: "CEATLTD", name: "CEAT Limited" },
  { symbol: "CENTURYTEX", name: "Century Textiles & Industries Limited" },
  { symbol: "CERA", name: "Cera Sanitaryware Limited" },
  { symbol: "CHAMBLFERT", name: "Chambal Fertilizers & Chemicals Limited" },
  { symbol: "CHENNPETRO", name: "Chennai Petroleum Corporation Limited" },
  { symbol: "CHOLAFIN", name: "Cholamandalam Investment and Finance Company Limited" },
  { symbol: "CIPLA", name: "Cipla Limited" },
  { symbol: "COALINDIA", name: "Coal India Limited" },
  { symbol: "COCHINSHIP", name: "Cochin Shipyard Limited" },
  { symbol: "COFORGE", name: "Coforge Limited" },
  { symbol: "COLPAL", name: "Colgate Palmolive (India) Limited" },
  { symbol: "CONCOR", name: "Container Corporation of India Limited" },
  { symbol: "COROMANDEL", name: "Coromandel International Limited" },
  { symbol: "CROMPTON", name: "Crompton Greaves Consumer Electricals Limited" },
  { symbol: "CUB", name: "City Union Bank Limited" },
  { symbol: "CUMMINSIND", name: "Cummins India Limited" },
  { symbol: "CYIENT", name: "Cyient Limited" },
  { symbol: "DABUR", name: "Dabur India Limited" },
  { symbol: "DALBHARAT", name: "Dalmia Bharat Limited" },
  { symbol: "DEEPAKNTR", name: "Deepak Nitrite Limited" },
  { symbol: "DELTACORP", name: "Delta Corp Limited" },
  { symbol: "DHANI", name: "Dhani Services Limited" },
  { symbol: "DHANUKA", name: "Dhanuka Agritech Limited" },
  { symbol: "DISHTV", name: "Dish TV India Limited" },
  { symbol: "DIVISLAB", name: "Divi's Laboratories Limited" },
  { symbol: "DLF", name: "DLF Limited" },
  { symbol: "DMART", name: "Avenue Supermarts Limited" },
  { symbol: "DRREDDY", name: "Dr. Reddy's Laboratories Limited" },
  { symbol: "EICHERMOT", name: "Eicher Motors Limited" },
  { symbol: "EIDPARRY", name: "EID Parry (India) Limited" },
  { symbol: "EIHOTEL", name: "EIH Limited" },
  { symbol: "ELGIEQUIP", name: "Elgi Equipments Limited" },
  { symbol: "EMAMILTD", name: "Emami Limited" },
  { symbol: "ENDURANCE", name: "Endurance Technologies Limited" },
  { symbol: "ENGINERSIN", name: "Engineers India Limited" },
  { symbol: "EQUITAS", name: "Equitas Holdings Limited" },
  { symbol: "ERIS", name: "Eris Lifesciences Limited" },
  { symbol: "ESCORTS", name: "Escorts Limited" },
  { symbol: "ESSELPACK", name: "Essel Propack Limited" },
  { symbol: "EXIDEIND", name: "Exide Industries Limited" },
  { symbol: "FEDERALBNK", name: "Federal Bank Limited" },
  { symbol: "FINEORG", name: "Fine Organic Industries Limited" },
  { symbol: "FINOLEX", name: "Finolex Cables Limited" },
  { symbol: "FINPIPE", name: "Finolex Industries Limited" },
  { symbol: "FLUOROCHEM", name: "Gujarat Fluorochemicals Limited" },
  { symbol: "FORTIS", name: "Fortis Healthcare Limited" },
  { symbol: "GAIL", name: "GAIL (India) Limited" },
  { symbol: "GESHIP", name: "The Great Eastern Shipping Company Limited" },
  { symbol: "GICRE", name: "General Insurance Corporation of India" },
  { symbol: "GILLETTE", name: "Gillette India Limited" },
  { symbol: "GLAXO", name: "GlaxoSmithKline Pharmaceuticals Limited" },
  { symbol: "GLENMARK", name: "Glenmark Pharmaceuticals Limited" },
  { symbol: "GMRINFRA", name: "GMR Infrastructure Limited" },
  { symbol: "GNFC", name: "Gujarat Narmada Valley Fertilizers & Chemicals Limited" },
  { symbol: "GODREJCP", name: "Godrej Consumer Products Limited" },
  { symbol: "GODREJIND", name: "Godrej Industries Limited" },
  { symbol: "GODREJPROP", name: "Godrej Properties Limited" },
  { symbol: "GRANULES", name: "Granules India Limited" },
  { symbol: "GRAPHITE", name: "Graphite India Limited" },
  { symbol: "GRASIM", name: "Grasim Industries Limited" },
  { symbol: "GREAVES", name: "Greaves Cotton Limited" },
  { symbol: "GRINDWELL", name: "Grindwell Norton Limited" },
  { symbol: "GSFC", name: "Gujarat State Fertilizers & Chemicals Limited" },
  { symbol: "GSPL", name: "Gujarat State Petronet Limited" },
  { symbol: "GUJALKALI", name: "Gujarat Alkalies and Chemicals Limited" },
  { symbol: "GUJGASLTD", name: "Gujarat Gas Limited" },
  { symbol: "GULFOILLUB", name: "Gulf Oil Lubricants India Limited" },
  { symbol: "HAL", name: "Hindustan Aeronautics Limited" },
  { symbol: "HAVELLS", name: "Havells India Limited" },
  { symbol: "HCLTECH", name: "HCL Technologies Limited" },
  { symbol: "HDFCAMC", name: "HDFC Asset Management Company Limited" },
  { symbol: "HDFCBANK", name: "HDFC Bank Limited" },
  { symbol: "HDFCLIFE", name: "HDFC Life Insurance Company Limited" },
  { symbol: "HEROMOTOCO", name: "Hero MotoCorp Limited" },
  { symbol: "HINDALCO", name: "Hindalco Industries Limited" },
  { symbol: "HINDCOPPER", name: "Hindustan Copper Limited" },
  { symbol: "HINDPETRO", name: "Hindustan Petroleum Corporation Limited" },
  { symbol: "HINDUNILVR", name: "Hindustan Unilever Limited" },
  { symbol: "HINDZINC", name: "Hindustan Zinc Limited" },
  { symbol: "HONAUT", name: "Honeywell Automation India Limited" },
  { symbol: "HPCL", name: "Hindustan Petroleum Corporation Limited" },
  { symbol: "HUDCO", name: "Housing & Urban Development Corporation Limited" },
  { symbol: "IBREALEST", name: "Indiabulls Real Estate Limited" },
  { symbol: "ICICIBANK", name: "ICICI Bank Limited" },
  { symbol: "ICICIGI", name: "ICICI Lombard General Insurance Company Limited" },
  { symbol: "ICICIPRULI", name: "ICICI Prudential Life Insurance Company Limited" },
  { symbol: "IDEA", name: "Vodafone Idea Limited" },
  { symbol: "IDFC", name: "IDFC Limited" },
  { symbol: "IDFCFIRSTB", name: "IDFC First Bank Limited" },
  { symbol: "IEX", name: "Indian Energy Exchange Limited" },
  { symbol: "IGL", name: "Indraprastha Gas Limited" },
  { symbol: "INDHOTEL", name: "The Indian Hotels Company Limited" },
  { symbol: "INDIACEM", name: "The India Cements Limited" },
  { symbol: "INDIAMART", name: "IndiaMART InterMESH Limited" },
  { symbol: "INDIANB", name: "Indian Bank" },
  { symbol: "INDIGO", name: "InterGlobe Aviation Limited" },
  { symbol: "INDOCO", name: "Indoco Remedies Limited" },
  { symbol: "INDUSINDBK", name: "IndusInd Bank Limited" },
  { symbol: "INFIBEAM", name: "Infibeam Avenues Limited" },
  { symbol: "INFY", name: "Infosys Limited" },
  { symbol: "INOXLEISUR", name: "INOX Leisures Limited" },
  { symbol: "INOXWIND", name: "Inox Wind Limited" },
  { symbol: "INSECTICID", name: "Insecticides (India) Limited" },
  { symbol: "IOC", name: "Indian Oil Corporation Limited" },
  { symbol: "IPCALAB", name: "IPCA Laboratories Limited" },
  { symbol: "IRB", name: "IRB Infrastructure Developers Limited" },
  { symbol: "IRCTC", name: "Indian Railway Catering and Tourism Corporation Limited" },
  { symbol: "ISEC", name: "ICICI Securities Limited" },
  { symbol: "ITC", name: "ITC Limited" },
  { symbol: "ITDC", name: "India Tourism Development Corporation Limited" },
  { symbol: "ITI", name: "ITI Limited" },
  { symbol: "JBCHEPHARM", name: "JB Chemicals & Pharmaceuticals Limited" },
  { symbol: "JCHAC", name: "Johnson Controls-Hitachi Air Conditioning India Limited" },
  { symbol: "JINDALSAW", name: "Jindal Saw Limited" },
  { symbol: "JINDALSTEL", name: "Jindal Steel & Power Limited" },
  { symbol: "JKCEMENT", name: "JK Cement Limited" },
  { symbol: "JKLAKSHMI", name: "JK Lakshmi Cement Limited" },
  { symbol: "JKPAPER", name: "JK Paper Limited" },
  { symbol: "JMFINANCIL", name: "JM Financial Limited" },
  { symbol: "JSW", name: "JSW Energy Limited" },
  { symbol: "JSWSTEEL", name: "JSW Steel Limited" },
  { symbol: "JUBLFOOD", name: "Jubilant FoodWorks Limited" },
  { symbol: "JUBLINDS", name: "Jubilant Industries Limited" },
  { symbol: "JUSTDIAL", name: "Just Dial Limited" },
  { symbol: "JYOTHYLAB", name: "Jyothy Labs Limited" },
  { symbol: "KAJARIACER", name: "Kajaria Ceramics Limited" },
  { symbol: "KANSAINER", name: "Kansai Nerolac Paints Limited" },
  { symbol: "KARURVYSYA", name: "Karur Vysya Bank Limited" },
  { symbol: "KEC", name: "KEC International Limited" },
  { symbol: "KIMS", name: "Krishna Institute of Medical Sciences Limited" },
  { symbol: "KOTAKBANK", name: "Kotak Mahindra Bank Limited" },
  { symbol: "KRBL", name: "KRBL Limited" },
  { symbol: "L&TFH", name: "L&T Finance Holdings Limited" },
  { symbol: "LALPATHLAB", name: "Dr. Lal PathLabs Limited" },
  { symbol: "LAURUSLABS", name: "Laurus Labs Limited" },
  { symbol: "LICHSGFIN", name: "LIC Housing Finance Limited" },
  { symbol: "LIFEINSUR", name: "Life Insurance Corporation of India" },
  { symbol: "LT", name: "Larsen & Toubro Limited" },
  { symbol: "LTIM", name: "LTIMindtree Limited" },
  { symbol: "LTTS", name: "L&T Technology Services Limited" },
  { symbol: "LUPIN", name: "Lupin Limited" },
  { symbol: "LXCHEM", name: "Laxmi Organic Industries Limited" },
  { symbol: "M&M", name: "Mahindra & Mahindra Limited" },
  { symbol: "M&MFIN", name: "Mahindra & Mahindra Financial Services Limited" },
  { symbol: "MARICO", name: "Marico Limited" },
  { symbol: "MARUTI", name: "Maruti Suzuki India Limited" },
  { symbol: "MCDOWELL-N", name: "United Spirits Limited" },
  { symbol: "MCX", name: "Multi Commodity Exchange of India Limited" },
  { symbol: "METROPOLIS", name: "Metropolis Healthcare Limited" },
  { symbol: "MGL", name: "Mahanagar Gas Limited" },
  { symbol: "MHRIL", name: "Mahindra Holidays & Resorts India Limited" },
  { symbol: "MINDACORP", name: "Minda Corporation Limited" },
  { symbol: "MINDAIND", name: "Minda Industries Limited" },
  { symbol: "MINDTREE", name: "Mindtree Limited" },
  { symbol: "MFSL", name: "Max Financial Services Limited" },
  { symbol: "MPHASIS", name: "Mphasis Limited" },
  { symbol: "MRF", name: "MRF Limited" },
  { symbol: "MUTHOOTFIN", name: "Muthoot Finance Limited" },
  { symbol: "NATIONALUM", name: "National Aluminium Company Limited" },
  { symbol: "NAUKRI", name: "Info Edge (India) Limited" },
  { symbol: "NAVINFLUOR", name: "Navin Fluorine International Limited" },
  { symbol: "NESTLEIND", name: "Nestle India Limited" },
  { symbol: "NMDC", name: "NMDC Limited" },
  { symbol: "NTPC", name: "NTPC Limited" },
  { symbol: "OBEROIRLTY", name: "Oberoi Realty Limited" },
  { symbol: "OFSS", name: "Oracle Financial Services Software Limited" },
  { symbol: "OIL", name: "Oil India Limited" },
  { symbol: "ONGC", name: "Oil and Natural Gas Corporation Limited" },
  { symbol: "PAYTM", name: "One 97 Communications Limited" },
  { symbol: "PGHH", name: "Procter & Gamble Hygiene and Health Care Limited" },
  { symbol: "PIDILITIND", name: "Pidilite Industries Limited" },
  { symbol: "PIIND", name: "PI Industries Limited" },
  { symbol: "PNB", name: "Punjab National Bank" },
  { symbol: "POLYCAB", name: "Polycab India Limited" },
  { symbol: "POWERGRID", name: "Power Grid Corporation of India Limited" },
  { symbol: "PVRINOX", name: "PVR INOX Limited" },
  { symbol: "QUESS", name: "Quess Corp Limited" },
  { symbol: "RAMCOCEM", name: "The Ramco Cements Limited" },
  { symbol: "RBLBANK", name: "RBL Bank Limited" },
  { symbol: "RECLTD", name: "REC Limited" },
  { symbol: "RELIANCE", name: "Reliance Industries Limited" },
  { symbol: "SAIL", name: "Steel Authority of India Limited" },
  { symbol: "SBICARD", name: "SBI Cards and Payment Services Limited" },
  { symbol: "SBILIFE", name: "SBI Life Insurance Company Limited" },
  { symbol: "SBIN", name: "State Bank of India" },
  { symbol: "SHREECEM", name: "Shree Cement Limited" },
  { symbol: "SIEMENS", name: "Siemens Limited" },
  { symbol: "SRF", name: "SRF Limited" },
  { symbol: "SUNPHARMA", name: "Sun Pharmaceutical Industries Limited" },
  { symbol: "SUNTV", name: "Sun TV Network Limited" },
  { symbol: "SUZLON", name: "Suzlon Energy Limited" },
  { symbol: "TATACHEM", name: "Tata Chemicals Limited" },
  { symbol: "TATACOMM", name: "Tata Communications Limited" },
  { symbol: "TATACONSUM", name: "Tata Consumer Products Limited" },
  { symbol: "TATAELXSI", name: "Tata Elxsi Limited" },
  { symbol: "TATAMOTORS", name: "Tata Motors Limited" },
  { symbol: "TATAPOWER", name: "Tata Power Company Limited" },
  { symbol: "TATASTEEL", name: "Tata Steel Limited" },
  { symbol: "TCS", name: "Tata Consultancy Services Limited" },
  { symbol: "TECHM", name: "Tech Mahindra Limited" },
  { symbol: "TITAN", name: "Titan Company Limited" },
  { symbol: "TORNTPHARM", name: "Torrent Pharmaceuticals Limited" },
  { symbol: "TORNTPOWER", name: "Torrent Power Limited" },
  { symbol: "TRENT", name: "Trent Limited" },
  { symbol: "TVSMOTOR", name: "TVS Motor Company Limited" },
  { symbol: "UBL", name: "United Breweries Limited" },
  { symbol: "ULTRACEMCO", name: "UltraTech Cement Limited" },
  { symbol: "UNIONBANK", name: "Union Bank of India" },
  { symbol: "UPL", name: "UPL Limited" },
  { symbol: "VEDL", name: "Vedanta Limited" },
  { symbol: "VOLTAS", name: "Voltas Limited" },
  { symbol: "WIPRO", name: "Wipro Limited" },
  { symbol: "YESBANK", name: "Yes Bank Limited" },
  { symbol: "ZEEL", name: "Zee Entertainment Enterprises Limited" },
  { symbol: "ZOMATO", name: "Zomato Limited" }
]

export const INTERNATIONAL_STOCKS = [
  // === UNITED STATES ===
  // Technology - Large Cap
  { symbol: "AAPL", name: "Apple Inc." },
  { symbol: "MSFT", name: "Microsoft Corporation" },
  { symbol: "GOOGL", name: "Alphabet Inc. (Class A)" },
  { symbol: "GOOG", name: "Alphabet Inc. (Class C)" },
  { symbol: "AMZN", name: "Amazon.com Inc." },
  { symbol: "NVDA", name: "NVIDIA Corporation" },
  { symbol: "META", name: "Meta Platforms Inc." },
  { symbol: "TSLA", name: "Tesla, Inc." },
  { symbol: "NFLX", name: "Netflix Inc." },
  { symbol: "ORCL", name: "Oracle Corporation" },
  { symbol: "CRM", name: "Salesforce Inc." },
  { symbol: "ADBE", name: "Adobe Inc." },
  { symbol: "INTC", name: "Intel Corporation" },
  { symbol: "AMD", name: "Advanced Micro Devices Inc." },
  { symbol: "AVGO", name: "Broadcom Inc." },
  { symbol: "QCOM", name: "Qualcomm Incorporated" },
  { symbol: "PYPL", name: "PayPal Holdings Inc." },
  { symbol: "UBER", name: "Uber Technologies Inc." },
  { symbol: "ABNB", name: "Airbnb Inc." },
  
  // Healthcare & Pharmaceuticals
  { symbol: "JNJ", name: "Johnson & Johnson" },
  { symbol: "PFE", name: "Pfizer Inc." },
  { symbol: "UNH", name: "UnitedHealth Group Inc." },
  { symbol: "ABT", name: "Abbott Laboratories" },
  { symbol: "LLY", name: "Eli Lilly and Company" },
  { symbol: "BMY", name: "Bristol-Myers Squibb Company" },
  { symbol: "MRK", name: "Merck & Co. Inc." },
  { symbol: "TMO", name: "Thermo Fisher Scientific Inc." },
  { symbol: "DHR", name: "Danaher Corporation" },
  { symbol: "ABBV", name: "AbbVie Inc." },
  
  // Financial Services
  { symbol: "BRK.B", name: "Berkshire Hathaway Inc. Class B" },
  { symbol: "JPM", name: "JPMorgan Chase & Co." },
  { symbol: "BAC", name: "Bank of America Corporation" },
  { symbol: "WFC", name: "Wells Fargo & Company" },
  { symbol: "GS", name: "The Goldman Sachs Group Inc." },
  { symbol: "MS", name: "Morgan Stanley" },
  { symbol: "V", name: "Visa Inc." },
  { symbol: "MA", name: "Mastercard Incorporated" },
  { symbol: "AXP", name: "American Express Company" },
  { symbol: "COF", name: "Capital One Financial Corporation" },
  
  // Consumer & Retail
  { symbol: "WMT", name: "Walmart Inc." },
  { symbol: "PG", name: "The Procter & Gamble Company" },
  { symbol: "KO", name: "The Coca-Cola Company" },
  { symbol: "PEP", name: "PepsiCo Inc." },
  { symbol: "NKE", name: "NIKE Inc." },
  { symbol: "HD", name: "The Home Depot Inc." },
  { symbol: "MCD", name: "McDonald's Corporation" },
  { symbol: "DIS", name: "The Walt Disney Company" },
  { symbol: "SBUX", name: "Starbucks Corporation" },
  { symbol: "COST", name: "Costco Wholesale Corporation" },
  
  // Industrial & Energy
  { symbol: "GE", name: "General Electric Company" },
  { symbol: "CAT", name: "Caterpillar Inc." },
  { symbol: "BA", name: "The Boeing Company" },
  { symbol: "XOM", name: "Exxon Mobil Corporation" },
  { symbol: "CVX", name: "Chevron Corporation" },
  { symbol: "COP", name: "ConocoPhillips" },
  
  // === EUROPE ===
  // United Kingdom
  { symbol: "SHEL", name: "Shell plc" },
  { symbol: "AZN", name: "AstraZeneca PLC" },
  { symbol: "BP", name: "BP p.l.c." },
  { symbol: "HSBA.L", name: "HSBC Holdings plc" },
  { symbol: "UL", name: "Unilever PLC" },
  { symbol: "RIO", name: "Rio Tinto Group" },
  { symbol: "GSK", name: "GSK plc" },
  { symbol: "DGE.L", name: "Diageo plc" },
  { symbol: "GLEN.L", name: "Glencore plc" },
  { symbol: "LLOY.L", name: "Lloyds Banking Group plc" },
  { symbol: "BARC.L", name: "Barclays PLC" },
  { symbol: "BT-A.L", name: "BT Group plc" },
  { symbol: "TSCO.L", name: "Tesco PLC" },
  { symbol: "ULVR.L", name: "Unilever PLC" },
  { symbol: "REL.L", name: "RELX PLC" },
  
  // Germany
  { symbol: "SAP", name: "SAP SE" },
  { symbol: "ASML", name: "ASML Holding N.V." },
  { symbol: "SIE.DE", name: "Siemens AG" },
  { symbol: "ADS.DE", name: "Adidas AG" },
  { symbol: "BMW.DE", name: "Bayerische Motoren Werke AG" },
  { symbol: "VOW3.DE", name: "Volkswagen AG" },
  { symbol: "BAS.DE", name: "BASF SE" },
  { symbol: "ALV.DE", name: "Allianz SE" },
  { symbol: "DBK.DE", name: "Deutsche Bank AG" },
  { symbol: "DAI.DE", name: "Mercedes-Benz Group AG" },
  { symbol: "MUV2.DE", name: "Munich Re" },
  { symbol: "DTE.DE", name: "Deutsche Telekom AG" },
  { symbol: "BEI.DE", name: "Beiersdorf AG" },
  { symbol: "HEN3.DE", name: "Henkel AG & Co. KGaA" },
  { symbol: "IFX.DE", name: "Infineon Technologies AG" },
  
  // France
  { symbol: "MC.PA", name: "LVMH Moët Hennessy Louis Vuitton SE" },
  { symbol: "OR.PA", name: "L'Oréal S.A." },
  { symbol: "TTE", name: "TotalEnergies SE" },
  { symbol: "SAN.PA", name: "Sanofi" },
  { symbol: "BNP.PA", name: "BNP Paribas" },
  { symbol: "AIR.PA", name: "Airbus SE" },
  { symbol: "CA.PA", name: "Carrefour SA" },
  { symbol: "AI.PA", name: "Air Liquide S.A." },
  { symbol: "DG.PA", name: "Vinci SA" },
  { symbol: "BN.PA", name: "Danone S.A." },
  { symbol: "KER.PA", name: "Kering SA" },
  { symbol: "RMS.PA", name: "Hermès International S.A." },
  { symbol: "SU.PA", name: "Schneider Electric S.E." },
  { symbol: "EL.PA", name: "EssilorLuxottica SA" },
  
  // Netherlands
  { symbol: "HEIA.AS", name: "Heineken N.V." },
  { symbol: "INGA.AS", name: "ING Groep N.V." },
  { symbol: "PHIA.AS", name: "Koninklijke Philips N.V." },
  { symbol: "UNA.AS", name: "Unilever N.V." },
  { symbol: "RDSA.AS", name: "Royal Dutch Shell plc" },
  { symbol: "ADYEN.AS", name: "Adyen N.V." },
  { symbol: "ASMI.AS", name: "ASM International N.V." },
  { symbol: "BESI.AS", name: "BE Semiconductor Industries N.V." },
  
  // Switzerland
  { symbol: "NESN.SW", name: "Nestlé S.A." },
  { symbol: "NOVN.SW", name: "Novartis AG" },
  { symbol: "ROG.SW", name: "Roche Holding AG" },
  { symbol: "UHR.SW", name: "The Swatch Group AG" },
  { symbol: "UBSG.SW", name: "UBS Group AG" },
  { symbol: "ZURN.SW", name: "Zurich Insurance Group AG" },
  { symbol: "CSGN.SW", name: "Credit Suisse Group AG" },
  { symbol: "ABBN.SW", name: "ABB Ltd." },
  { symbol: "GIVN.SW", name: "Givaudan SA" },
  { symbol: "LONN.SW", name: "Lonza Group Ltd." },
  { symbol: "CFR.SW", name: "Compagnie Financière Richemont SA" },
  
  // Italy
  { symbol: "ENEL.MI", name: "Enel SpA" },
  { symbol: "ENI.MI", name: "Eni S.p.A." },
  { symbol: "UCG.MI", name: "UniCredit S.p.A." },
  { symbol: "ISP.MI", name: "Intesa Sanpaolo S.p.A." },
  { symbol: "TIT.MI", name: "Telecom Italia S.p.A." },
  { symbol: "FCA.MI", name: "Stellantis N.V." },
  { symbol: "G.MI", name: "Assicurazioni Generali S.p.A." },
  { symbol: "RACE.MI", name: "Ferrari N.V." },
  { symbol: "LUX.MI", name: "Luxottica Group S.p.A." },
  
  // Spain
  { symbol: "SAN.MC", name: "Banco Santander, S.A." },
  { symbol: "TEF.MC", name: "Telefónica, S.A." },
  { symbol: "IBE.MC", name: "Iberdrola, S.A." },
  { symbol: "BBVA.MC", name: "Banco Bilbao Vizcaya Argentaria, S.A." },
  { symbol: "ITX.MC", name: "Industria de Diseño Textil, S.A." },
  { symbol: "REP.MC", name: "Repsol, S.A." },
  
  // === ASIA PACIFIC ===
  // Japan
  { symbol: "7203.T", name: "Toyota Motor Corporation" },
  { symbol: "6758.T", name: "Sony Group Corporation" },
  { symbol: "8035.T", name: "Tokyo Electron Limited" },
  { symbol: "9984.T", name: "SoftBank Group Corp." },
  { symbol: "6861.T", name: "Keyence Corporation" },
  { symbol: "4543.T", name: "Terumo Corporation" },
  { symbol: "8306.T", name: "Mitsubishi UFJ Financial Group, Inc." },
  { symbol: "7267.T", name: "Honda Motor Co., Ltd." },
  { symbol: "9432.T", name: "Nippon Telegraph and Telephone Corporation" },
  { symbol: "4502.T", name: "Takeda Pharmaceutical Company Limited" },
  { symbol: "8058.T", name: "Mitsubishi Corporation" },
  { symbol: "7974.T", name: "Nintendo Co., Ltd." },
  { symbol: "4568.T", name: "Daiichi Sankyo Company, Limited" },
  { symbol: "9983.T", name: "Fast Retailing Co., Ltd." },
  { symbol: "6098.T", name: "Recruit Holdings Co., Ltd." },
  { symbol: "6954.T", name: "Fanuc Corporation" },
  { symbol: "8031.T", name: "Mitsui & Co., Ltd." },
  { symbol: "4661.T", name: "Oriental Land Co., Ltd." },
  { symbol: "7751.T", name: "Canon Inc." },
  { symbol: "9434.T", name: "SoftBank Corp." },
  
  // China & Hong Kong
  { symbol: "0700.HK", name: "Tencent Holdings Limited" },
  { symbol: "9988.HK", name: "Alibaba Group Holding Limited" },
  { symbol: "9618.HK", name: "JD.com, Inc." },
  { symbol: "3690.HK", name: "Meituan" },
  { symbol: "1398.HK", name: "Industrial and Commercial Bank of China Limited" },
  { symbol: "0939.HK", name: "China Construction Bank Corporation" },
  { symbol: "0883.HK", name: "CNOOC Limited" },
  { symbol: "0388.HK", name: "Hong Kong Exchanges and Clearing Limited" },
  { symbol: "1299.HK", name: "AIA Group Limited" },
  { symbol: "2318.HK", name: "Ping An Insurance (Group) Company of China, Ltd." },
  { symbol: "0005.HK", name: "HSBC Holdings plc" },
  { symbol: "2020.HK", name: "ANTA Sports Products Limited" },
  { symbol: "1810.HK", name: "Xiaomi Corporation" },
  { symbol: "2628.HK", name: "China Life Insurance Company Limited" },
  { symbol: "1928.HK", name: "Sands China Ltd." },
  { symbol: "BIDU", name: "Baidu, Inc." },
  { symbol: "BABA", name: "Alibaba Group Holding Limited" },
  { symbol: "JD", name: "JD.com, Inc." },
  { symbol: "NTES", name: "NetEase, Inc." },
  { symbol: "PDD", name: "PDD Holdings Inc." },
  { symbol: "TME", name: "Tencent Music Entertainment Group" },
  { symbol: "BILI", name: "Bilibili Inc." },
  { symbol: "NIO", name: "NIO Inc." },
  { symbol: "XPEV", name: "XPeng Inc." },
  { symbol: "LI", name: "Li Auto Inc." },
  
  // South Korea
  { symbol: "005930.KS", name: "Samsung Electronics Co., Ltd." },
  { symbol: "000660.KS", name: "SK Hynix Inc." },
  { symbol: "035420.KS", name: "NAVER Corporation" },
  { symbol: "207940.KS", name: "Samsung Biologics Co., Ltd." },
  { symbol: "005380.KS", name: "Hyundai Motor Company" },
  { symbol: "012330.KS", name: "Hyundai Mobis Co., Ltd." },
  { symbol: "028260.KS", name: "Samsung C&T Corporation" },
  { symbol: "066570.KS", name: "LG Electronics Inc." },
  { symbol: "096770.KS", name: "SK Innovation Co., Ltd." },
  { symbol: "003550.KS", name: "LG Corp." },
  { symbol: "017670.KS", name: "SK Telecom Co., Ltd." },
  { symbol: "030200.KS", name: "KT Corporation" },
  { symbol: "051910.KS", name: "LG Chem, Ltd." },
  { symbol: "323410.KS", name: "Kakao Corp." },
  { symbol: "018260.KS", name: "Samsung SDS Co., Ltd." },
  
  // Taiwan
  { symbol: "2330.TW", name: "Taiwan Semiconductor Manufacturing Company Limited" },
  { symbol: "2454.TW", name: "MediaTek Inc." },
  { symbol: "2317.TW", name: "Hon Hai Precision Industry Co., Ltd." },
  { symbol: "2412.TW", name: "Chunghwa Telecom Co., Ltd." },
  { symbol: "1301.TW", name: "Formosa Plastics Corporation" },
  { symbol: "1303.TW", name: "Nan Ya Plastics Corporation" },
  { symbol: "2881.TW", name: "Fubon Financial Holding Co., Ltd." },
  { symbol: "2882.TW", name: "Cathay Financial Holding Co., Ltd." },
  { symbol: "2308.TW", name: "Delta Electronics, Inc." },
  { symbol: "2609.TW", name: "Yang Ming Marine Transport Corporation" },
  
  // Australia
  { symbol: "CBA.AX", name: "Commonwealth Bank of Australia" },
  { symbol: "BHP.AX", name: "BHP Group Limited" },
  { symbol: "WBC.AX", name: "Westpac Banking Corporation" },
  { symbol: "ANZ.AX", name: "Australia and New Zealand Banking Group Limited" },
  { symbol: "CSL.AX", name: "CSL Limited" },
  { symbol: "NAB.AX", name: "National Australia Bank Limited" },
  { symbol: "WES.AX", name: "Wesfarmers Limited" },
  { symbol: "RIO.AX", name: "Rio Tinto Limited" },
  { symbol: "TCL.AX", name: "Transurban Group" },
  { symbol: "TLS.AX", name: "Telstra Corporation Limited" },
  { symbol: "WOW.AX", name: "Woolworths Group Limited" },
  { symbol: "FMG.AX", name: "Fortescue Metals Group Limited" },
  { symbol: "MQG.AX", name: "Macquarie Group Limited" },
  { symbol: "WPL.AX", name: "Woodside Energy Group Ltd" },
  { symbol: "REA.AX", name: "REA Group Ltd" },
  
  // Singapore
  { symbol: "D05.SI", name: "DBS Group Holdings Ltd" },
  { symbol: "O39.SI", name: "Oversea-Chinese Banking Corporation Limited" },
  { symbol: "U11.SI", name: "United Overseas Bank Limited" },
  { symbol: "Z74.SI", name: "Singapore Telecommunications Limited" },
  { symbol: "G13.SI", name: "Genting Singapore Limited" },
  { symbol: "C52.SI", name: "ComfortDelGro Corporation Limited" },
  { symbol: "C6L.SI", name: "Singapore Airlines Limited" },
  { symbol: "H78.SI", name: "Hongkong Land Holdings Limited" },
  { symbol: "J37.SI", name: "Jardine Matheson Holdings Limited" },
  
  // === EMERGING MARKETS ===
  // Brazil
  { symbol: "VALE", name: "Vale S.A." },
  { symbol: "ITUB", name: "Itaú Unibanco Holding S.A." },
  { symbol: "BBD", name: "Banco Bradesco S.A." },
  { symbol: "ABEV", name: "Ambev S.A." },
  { symbol: "PBR", name: "Petróleo Brasileiro S.A. - Petrobras" },
  { symbol: "SUZB3.SA", name: "Suzano S.A." },
  { symbol: "WEGE3.SA", name: "WEG S.A." },
  { symbol: "MGLU3.SA", name: "Magazine Luiza S.A." },
  { symbol: "PETR4.SA", name: "Petróleo Brasileiro S.A. - Petrobras" },
  { symbol: "BBDC4.SA", name: "Banco Bradesco S.A." },
  { symbol: "ITSA4.SA", name: "Itaúsa S.A." },
  { symbol: "ABEV3.SA", name: "Ambev S.A." },
  { symbol: "B3SA3.SA", name: "B3 S.A. - Brasil, Bolsa, Balcão" },
  { symbol: "RENT3.SA", name: "Localiza Rent a Car S.A." },
  { symbol: "LREN3.SA", name: "Lojas Renner S.A." },
  
  // Mexico
  { symbol: "AMXL", name: "América Móvil, S.A.B. de C.V." },
  { symbol: "TLEVCP.MX", name: "Televisa, S.A.B. de C.V." },
  { symbol: "GFNORTEO.MX", name: "Grupo Financiero Banorte, S.A.B. de C.V." },
  { symbol: "WALMEX.MX", name: "Wal-Mart de México, S.A.B. de C.V." },
  { symbol: "CEMEXCPO.MX", name: "CEMEX, S.A.B. de C.V." },
  { symbol: "GMEXICO.MX", name: "Grupo México, S.A.B. de C.V." },
  
  // South Africa
  { symbol: "NPN.JO", name: "Naspers Limited" },
  { symbol: "PRX.JO", name: "Prosus N.V." },
  { symbol: "SHP.JO", name: "Shoprite Holdings Ltd." },
  { symbol: "FSR.JO", name: "FirstRand Limited" },
  { symbol: "SBK.JO", name: "Standard Bank Group Limited" },
  { symbol: "ABG.JO", name: "Absa Group Limited" },
  { symbol: "SOL.JO", name: "Sasol Limited" },
  { symbol: "AGL.JO", name: "Anglo American plc" },
  { symbol: "BVT.JO", name: "The Bidvest Group Limited" },
  { symbol: "NED.JO", name: "Nedbank Group Limited" },
  
  // Russia (Note: Many Russian stocks are currently suspended/restricted)
  { symbol: "SBER.ME", name: "Sberbank of Russia" },
  { symbol: "GAZP.ME", name: "Gazprom" },
  { symbol: "LKOH.ME", name: "Lukoil" },
  { symbol: "NVTK.ME", name: "Novatek" },
  { symbol: "ROSN.ME", name: "Rosneft" },
  { symbol: "YNDX.ME", name: "Yandex" },
  { symbol: "MAIL.ME", name: "Mail.ru Group" },
  { symbol: "MTSS.ME", name: "Mobile TeleSystems" },
  { symbol: "AFLT.ME", name: "Aeroflot" },
  { symbol: "MAGN.ME", name: "Magnitogorsk Iron and Steel Works" },
  
  // India (ADRs)
  { symbol: "INFY", name: "Infosys Limited" },
  { symbol: "WIT", name: "Wipro Limited" },
  { symbol: "HDB", name: "HDFC Bank Limited" },
  { symbol: "IBN", name: "ICICI Bank Limited" },
  { symbol: "TTM", name: "Tata Motors Limited" },
  { symbol: "VEDL", name: "Vedanta Limited" },
  { symbol: "RDY", name: "Dr. Reddy's Laboratories Ltd." },
  { symbol: "SIFY", name: "Sify Technologies Limited" },
  { symbol: "REDF", name: "Rediff.com India Limited" },
  { symbol: "MMYT", name: "MakeMyTrip Limited" },
  
  // === CANADA ===
  { symbol: "SHOP.TO", name: "Shopify Inc." },
  { symbol: "RY.TO", name: "Royal Bank of Canada" },
  { symbol: "TD.TO", name: "The Toronto-Dominion Bank" },
  { symbol: "BNS.TO", name: "The Bank of Nova Scotia" },
  { symbol: "BMO.TO", name: "Bank of Montreal" },
  { symbol: "CNR.TO", name: "Canadian National Railway Company" },
  { symbol: "CP.TO", name: "Canadian Pacific Railway Limited" },
  { symbol: "ENB.TO", name: "Enbridge Inc." },
  { symbol: "TRP.TO", name: "TC Energy Corporation" },
  { symbol: "SU.TO", name: "Suncor Energy Inc." },
  { symbol: "CNQ.TO", name: "Canadian Natural Resources Limited" },
  { symbol: "IMO.TO", name: "Imperial Oil Limited" },
  { symbol: "L.TO", name: "Loblaw Companies Limited" },
  { symbol: "MG.TO", name: "Magna International Inc." },
  { symbol: "ATD.TO", name: "Alimentation Couche-Tard Inc." },
  { symbol: "WN.TO", name: "George Weston Limited" },
  { symbol: "ABX.TO", name: "Barrick Gold Corporation" },
  { symbol: "NTR.TO", name: "Nutrien Ltd." },
  { symbol: "CCL-B.TO", name: "CCL Industries Inc." },
  { symbol: "CSU.TO", name: "Constellation Software Inc." },
  
  // === NORDIC COUNTRIES ===
  // Denmark
  { symbol: "NOVO-B.CO", name: "Novo Nordisk A/S" },
  { symbol: "ORSTED.CO", name: "Ørsted A/S" },
  { symbol: "MAERSK-B.CO", name: "A.P. Møller - Mærsk A/S" },
  { symbol: "CARLB.CO", name: "Carlsberg A/S" },
  { symbol: "DANSKE.CO", name: "Danske Bank A/S" },
  { symbol: "PANDORA.CO", name: "Pandora A/S" },
  { symbol: "NZYM-B.CO", name: "Novozymes A/S" },
  { symbol: "VESTAS.CO", name: "Vestas Wind Systems A/S" },
  { symbol: "GN.CO", name: "GN Store Nord A/S" },
  { symbol: "COLOPLAST-B.CO", name: "Coloplast A/S" },
  
  // Sweden
  { symbol: "VOLV-B.ST", name: "Volvo AB" },
  { symbol: "ERIC-B.ST", name: "Telefonaktiebolaget LM Ericsson" },
  { symbol: "SEB-A.ST", name: "Skandinaviska Enskilda Banken AB" },
  { symbol: "SWED-A.ST", name: "Swedbank AB" },
  { symbol: "ATLAS-B.ST", name: "Atlas Copco AB" },
  { symbol: "SAND.ST", name: "Sandvik AB" },
  { symbol: "SKF-B.ST", name: "SKF AB" },
  { symbol: "HEXA-B.ST", name: "Hexagon AB" },
  { symbol: "INVE-B.ST", name: "Investor AB" },
  { symbol: "ESSITY-B.ST", name: "Essity AB" },
  
  // Norway
  { symbol: "EQNR.OL", name: "Equinor ASA" },
  { symbol: "TEL.OL", name: "Telenor ASA" },
  { symbol: "MOWI.OL", name: "Mowi ASA" },
  { symbol: "YAR.OL", name: "Yara International ASA" },
  { symbol: "NHY.OL", name: "Norsk Hydro ASA" },
  { symbol: "DNB.OL", name: "DNB ASA" },
  { symbol: "SCATC.OL", name: "Scatec ASA" },
  { symbol: "SUBSEA.OL", name: "Subsea 7 S.A." },
  { symbol: "ORKLA.OL", name: "Orkla ASA" },
  { symbol: "SALM.OL", name: "SalMar ASA" },
  
  // Finland
  { symbol: "NOKIA.HE", name: "Nokia Corporation" },
  { symbol: "SAMPO.HE", name: "Sampo Oyj" },
  { symbol: "FORTUM.HE", name: "Fortum Corporation" },
  { symbol: "STERV.HE", name: "Stora Enso Oyj" },
  { symbol: "UPM.HE", name: "UPM-Kymmene Corporation" },
  { symbol: "METSO.HE", name: "Metso Corporation" },
  { symbol: "KONE.HE", name: "KONE Corporation" },
  { symbol: "ELISA.HE", name: "Elisa Corporation" },
  { symbol: "TYRES.HE", name: "Nokian Tyres plc" },
  { symbol: "WITTED.HE", name: "Wärtsilä Corporation" },
]

export function searchStocks(query: string): Stock[] {
  if (!query || query.length < 1) return []
  
  const lowerQuery = query.toLowerCase()
  
  // Search through both Indian and international stocks
  const indianResults = INDIAN_STOCKS.filter(stock => 
    stock.symbol.toLowerCase().includes(lowerQuery) ||
    stock.name.toLowerCase().includes(lowerQuery)
  )
  
  const internationalResults = INTERNATIONAL_STOCKS.filter(stock => 
    stock.symbol.toLowerCase().includes(lowerQuery) ||
    stock.name.toLowerCase().includes(lowerQuery)
  )
  
  // Combine results with Indian stocks first, then international
  const allResults = [...indianResults, ...internationalResults]
  
  return allResults.slice(0, 10) // Limit to 10 results
}

export function findStockSymbols(text: string): string[] {
  const words = text.toUpperCase().split(/\s+/)
  const symbols = new Set<string>()
  
  for (const word of words) {
    const cleanWord = word.replace(/[^A-Z]/g, '')
    if (cleanWord && (
      INDIAN_STOCKS.some(stock => stock.symbol === cleanWord) ||
      INTERNATIONAL_STOCKS.some(stock => stock.symbol === cleanWord)
    )) {
      symbols.add(cleanWord)
    }
  }
  
  return Array.from(symbols)
} 